version: "3.8"
services:
  app:
    build: .
    ports:
      - "7020:7020"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/commit_ninja
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
  postgres:
    container_name: commit_ninja_db
    image: postgres:15.1
    hostname: localhost
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commit_ninja
    volumes:
      - postgres-commit-ninja:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-commit-ninja:
